FROM openjdk:17
ARG JAR_FILE=build/libs/*.jar
ARG PROPERTIES=src/main/resources/application.properties
ARG FIREBASE_KEY=src/main/resources/sportsit-test-firebase-adminsdk-z9zhb-71e9f2f186.json
ARG KEYSTORE=src/main/resources/keystore.p12
COPY ${JAR_FILE} app.jar
COPY ${PROPERTIES} resources/application.properties
COPY ${FIREBASE_KEY} resources/sportsit-test-firebase-adminsdk-z9zhb-71e9f2f186.json
COPY ${KEYSTORE} resources/keystore.p12
ENTRYPOINT ["java", "-jar", "/app.jar"]
